### PR TITLE
Got things working

### PR DESCRIPTION
**Pull request by watzon**
I ran `crystal tool format` on the project to get styles situated, updated the example file and put it in its own directory, and added a `shard.yml` so that it the project can be downloaded through Crystal shards.

I don't know if you plan on maintaining this, but I need it working for a shard I'm getting ready to write, so I'd be more than willing to take over if you don't want to worry about maintaining it.

### CODE REVIEW

**Comment by oprypin** [comment]
Ya know, this really rubbed me the wrong way, even starting with the title.

* > Got things working

  Implying they aren't working?

* > `crystal tool format`

  Its output is always atrocious, I will not accept it.

* > updated the example file and put it in its own directory

  How is this an improvement? For one thing, now the example is not standalone, it assumes being in this project's directory.

* > and added a `shard.yml` so that it the project can be downloaded through Crystal shards

  [Implying it can't?](https://github.com/search?q=crystal-dbus&type=Code)

* > I don't know if you plan on maintaining this

  Implying it's unmaintained?

* *adding yourself as author*

  That's pretty bold...

* *replacing gitignore with a worse version without a mention*

  Uh ok

> I'd be more than willing to take over

Considering this and the fact that I'm overly protective of my projects, might be easier to fork. Would be a shame to not be able to upstream features/bugfixes though, what with the mass re-format.

**Comment by oprypin** [comment]
I've separately updated code formatting to be more in line with commonly accepted styles.

https://github.com/oprypin/crystal-dbus/compare/9bd18d5a61f54e80e41bdae4b93236732d5d34c9...dc968b27c08c29e3abd48b615cd6cfbe2664d41d

**Comment by watzon** [comment]
Wasn't trying to offend. Just noticed it hadn't been updated in a while and when I forked it the example wouldn't run. It also doesn't show up on crystalshards.org because of the missing `shard.yml`. Glad you're still working on it.

**Comment by oprypin** [comment]
Addressed these concerns as well.
[`dc968b2...9d4ba8d`](https://github.com/oprypin/crystal-dbus/commits/9d4ba8dedb191d9d3fe62094eddaed32775612e1)

**Comment by watzon** [comment]
Thanks. Sorry if I offended you. I used this in a project a couple of years ago and I was surprised that I couldn't find it on crystalshards.org, so I figured I'd try and help it along. I'll probably delete my fork and re-fork. I need to see about adding support for properties, because they don't seem to be supported right now.

**Comment by oprypin** [comment]
Miiight be interested in https://github.com/voximity/crystal-dbus/commit/eaca68f5ce04416cbdee43563eb54c4a9107777d

**Comment by watzon** [comment]
Ooh yes. Too bad he hasn't responded yet, it would be nice to get that merged in.

**Pull request closed without merging**
